-- Users, characters and sessions schema for CoreZ
CREATE TABLE IF NOT EXISTS users (
	id INT AUTO_INCREMENT PRIMARY KEY,
	primary_identifier VARCHAR(128) NOT NULL UNIQUE,
	identifiers JSON DEFAULT NULL,
	name VARCHAR(128) DEFAULT NULL,
	first_seen TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	last_seen TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	total_play_seconds INT DEFAULT 0
);

CREATE TABLE IF NOT EXISTS characters (
	id INT AUTO_INCREMENT PRIMARY KEY,
	user_id INT NOT NULL,
	first_name VARCHAR(64) DEFAULT NULL,
	last_name VARCHAR(64) DEFAULT NULL,
	last_x DOUBLE DEFAULT NULL,
	last_y DOUBLE DEFAULT NULL,
	last_z DOUBLE DEFAULT NULL,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	is_active TINYINT(1) DEFAULT 1,
	FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);
